name: Deploy Terra Classic Station
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest    
    permissions:
      contents: read
      deployments: write
    env:
      CI: false
      NODE_OPTIONS: "--max_old_space_size=4096"
      REACT_APP_SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      GUARDARIAN_API_KEY: ${{ secrets.GUARDARIAN_API_KEY }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Installing Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: Installing dependencies
      run: npm install
    - name: Building project
      run: npm run build
    - name: Publish to Cloudflare Pages
      uses: cloudflare/pages-action@v1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        projectName: terra-classic-station
        directory: ./build
        gitHubToken: ${{ secrets.GITHUB_TOKEN }}
    - name: Create Sentry release
      uses: getsentry/action-release@v1
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
        SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      with:
        environment: production
